Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2021-06, with the labels that each got.

#139 Allow governor to be selected if deputation
  app/components/participation-list/mandataris-selector.js
Labels: enhancement

#138 Bugfix/store public setting of treatment
  app/components/behandeling-van-agendapunt.hbs
  app/components/behandeling-van-agendapunt.js
Labels: bug

#137 bugfix: provide read only view, so that once the agendapoint is published the voting is visible in the meeting
  app/components/behandeling-van-agendapunt.hbs
  app/components/treatment/voting/index.hbs
  app/components/treatment/voting/modal.hbs
Labels: bug, enhancement

#141 fix layout of publication preview (based on the work dieter did on the publication frontend)
  app/styles/project/_c-template.scss
Labels: bug
