Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2021-08, with the labels that each got.

#161 Improve wording around notification
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#160 Consume job for prepublishing
  app/services/publish.js
Labels: bug, enhancement

#162 BUGFIX: now you can sign and publish the same document and will be shown as such
  app/components/signatures/agenda/timeline-step.hbs
  app/components/signatures/behandeling/timeline-step.hbs
  app/components/signatures/besluitenlijst/timeline-step.hbs
  app/components/signatures/notulen/timeline-step.hbs
  app/components/signatures/timeline-step.hbs
  app/components/signatures/timeline-step.js
  app/controllers/meetings/publish/notulen.js
  app/services/publish.js
  app/templates/meetings/publish/notulen.hbs
Labels: bug

#163 lazy load uittreksels
  app/components/signatures/agenda/timeline-step.hbs
  app/components/signatures/behandeling/timeline-step.hbs
  app/components/signatures/behandeling/timeline-step.js
  app/components/signatures/besluitenlijst/timeline-step.hbs
  app/components/signatures/notulen/timeline-step.hbs
  app/components/signatures/timeline-step.hbs
  app/components/signatures/timeline-step.js
  app/config/custom-inflector-rules.js
  app/controllers/meetings/publish/uittreksels.js
  app/controllers/meetings/publish/uittreksels/index.js
  app/controllers/meetings/publish/uittreksels/show.js
  app/models/behandeling-van-agendapunt.js
  app/models/extract-preview.js
  app/router.js
  app/routes/meetings/publish/uittreksels.js
  app/routes/meetings/publish/uittreksels/index.js
  app/routes/meetings/publish/uittreksels/show.js
  app/styles/_shame.scss
  app/templates/meetings/publish/uittreksels.hbs
  app/templates/meetings/publish/uittreksels/index.hbs
  app/templates/meetings/publish/uittreksels/show.hbs
  app/templates/print/uittreksel.hbs
  package.json
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#167 Use task flow for preview, signing and publication of notulen
  app/controllers/meetings/publish/notulen.js
  app/services/mu-task.js
  app/services/publish.js
Labels: enhancement
