Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2021-07, with the labels that each got.

#144 Bump ember-rdfa-editor to v0.45.0
  package.json
Labels: internal

#140 Feature/get draft description
  app/components/agenda-manager/edit.hbs
  app/components/agenda-manager/edit.js
  app/services/document-service.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#145 bump import snippet plugin
  package.json
Labels: internal

#147 Add lerna-changelog
  .release-it.json
  package.json
Labels: internal

#148 Feature/show agendapoints as 1 based
  CHANGELOG.md
  app/components/agenda-manager/agenda-table/row.hbs
  package.json
Labels: enhancement

#143 Feature/file upload
  .release-it.json
  app/components/app-chrome.hbs
  app/components/au-file-upload.hbs
  app/components/au-file-upload.js
  app/components/document-attachments.hbs
  app/components/document-attachments.js
  app/config/custom-inflector-rules.js
  app/controllers/agendapoints/edit.js
  app/controllers/meetings/edit/treatment.js
  app/models/attachment.js
  app/models/document-container.js
  app/models/file.js
  app/styles/app.scss
  app/styles/project/_c-upload.scss
  app/templates/agendapoints/edit.hbs
  app/templates/meetings/edit/treatment.hbs
  package.json
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#149 Put voting modal buttons first
  app/components/treatment/voting/manage-voters.hbs
Labels: enhancement

#153 Bump editor to 0.46.1
  package.json
Labels: internal

#127 Bugfix/error publishing notulen
  app/controllers/meetings/publish/notulen.js
  app/templates/meetings/publish/notulen.hbs
Labels: bug

#146 updated app universum and changed from au button to au link
  app/components/behandeling-van-agendapunt.hbs
  app/components/behandeling-van-agendapunt.js
  app/components/meeting-form.hbs
  app/components/meeting-form.js
  package.json
Labels: enhancement

#151 Fixed behandeling publishing status was not being updated properly without page refresh
  app/components/behandeling-van-agendapunt.js
Labels: bug

#152 Feature/file upload
  app/components/document-attachments.hbs
  app/components/document-attachments.js
  app/controllers/agendapoints/edit.js
  app/controllers/meetings/edit/treatment.js
  app/services/document-service.js
  app/templates/agendapoints/edit.hbs
  app/templates/meetings/edit/treatment.hbs
  app/utils/constants.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement
