Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2021-09, with the labels that each got.

#168 Bump editor to v0.47.0
  package.json
Labels: internal

#150 full support for file attachments
  .drone.yml
  app/components/app-chrome.hbs
  app/components/au-file-upload.hbs
  app/components/au-file-upload.js
  app/components/document-attachments.hbs
  app/components/document-attachments.js
  app/config/custom-inflector-rules.js
  app/controllers/agendapoints/edit.js
  app/controllers/meetings/edit/treatment.js
  app/models/attachment.js
  app/models/document-container.js
  app/models/file.js
  app/routes/agendapoints/edit.js
  app/services/document-service.js
  app/styles/_shame.scss
  app/styles/app.scss
  app/styles/project/_c-upload.scss
  app/templates/agendapoints/edit.hbs
  app/templates/meetings/edit/treatment.hbs
  app/utils/constants.js
  package.json
  proxy/file-upload.conf
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#170 changed time format of intermission
  app/components/manage-intermissions/index.hbs
Labels: bug

#171 added a toggle to toggle all agendapoints to be public/private in notulen preview
  app/components/signatures/notulen/behandelingen-list.hbs
  app/components/signatures/notulen/timeline-step.hbs
  app/controllers/meetings/publish/notulen.js
  app/styles/project/_c-editor-preview.scss
  app/templates/meetings/publish/notulen.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#174 Add styling for tables still relying on webuniversum css
  app/components/participation-list/mandatarissen-table.hbs
  app/components/treatment/voting/voter-table.hbs
  app/styles/_shame.scss
Labels: bug

#175 Fixed page numbers in extract publication table
  app/templates/meetings/publish/uittreksels/index.hbs
Labels: bug

#180 [HOTFIX] Add updated items to changeset
  app/components/agenda-manager/agenda-context.js
Labels: bug

#181 Remove requirebranch config
  .release-it.json
Labels: internal

#176 Hide attachments behind feature flag
  app/components/app-chrome.hbs
  app/templates/meetings/edit/treatment.hbs
  config/environment.js
Labels: internal

#177 Calculated status based on the actual publication status of the extract
  app/components/signatures/publication-status.hbs
  app/components/signatures/publication-status.js
  app/routes/meetings/publish/uittreksels/index.js
  app/templates/meetings/publish/uittreksels/index.hbs
Labels: enhancement

#178 Fix notulen was not correctly reloaded under a very specific scenario
  app/controllers/meetings/publish/notulen.js
Labels: bug

#172 Feature/acmidm switch
  README.md
  app/controllers/inbox.js
  app/routes/switch-login.js
  app/templates/inbox.hbs
  app/templates/switch-login.hbs
  config/environment.js
Labels: enhancement

#183 bugfix: allow large file uploads
  Dockerfile
Labels: bug

#184 Fix/drag icon
  app/components/agenda-manager/agenda-table/row.hbs
  app/styles/_shame.scss
  app/styles/app.scss
  package.json
Labels: internal

#187 Bugfix/missing router config for switch login route
  CHANGELOG.md
  app/router.js
  package.json
Labels: bug

#185 use au-file-upload from appuniversum
  app/components/au-file-upload.hbs
  app/components/au-file-upload.js
  app/components/document-attachments.js
  package.json
Labels: internal

#190 added attachment counter to ap edit route, fixed bug with undefined length
  app/components/app-chrome.hbs
  app/templates/meetings/edit/treatment.hbs
Labels: bug

#192 Fix typo in outro component
  translations/en-us.yaml
Labels: bug

#189 use generator methods instead of fields in vote modal
  app/components/treatment/voting/modal.js
Labels: internal

#182 added agendapoint position to the select and the search
  app/components/agenda-manager/agenda-item-form/select-location.hbs
  app/components/agenda-manager/agenda-item-form/select-location.js
  app/components/agenda-manager/edit.hbs
Labels: enhancement

#188 correctly delete vote
  app/components/treatment/voting/modal.js
Labels: bug

#193 Feature/enable acmidm switch
  CHANGELOG.md
  config/environment.js
  package.json
Labels: enhancement

#195 fix editor scrolling issue
  app/styles/_deprecated.scss
Labels: bug

#198 Fix issue with double characters
  package.json
Labels: bug

#197 added an overview of attachments in meeting interface
  app/components/behandeling-van-agendapunt.hbs
  app/components/document-attachments.hbs
  app/components/readonly-text-box.hbs
  app/styles/app.scss
  app/styles/project/_c-meeting-chrome.scss
  app/styles/project/_c-upload.scss
Labels: enhancement
