Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-06, with the labels that each got.

#281 Fix chrome print bug
  app/styles/project/_u-print.scss
Labels: bug

#159 Feature/delete meetings
  app/components/delete-meeting.hbs
  app/components/delete-meeting.js
  app/components/meeting-form.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#283 irg archive
  app/config/constants.js
  app/models/document-container.js
  app/models/editor-document.js
  app/router.js
  app/routes/inbox.js
  app/routes/inbox/agendapoints.js
  app/routes/inbox/irg-archive.js
  app/routes/inbox/trash.js
  app/routes/irg-archive/show.js
  app/templates/inbox.hbs
  app/templates/inbox/irg-archive.hbs
  app/templates/irg-archive/show.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#285 Introducing ember-plausible
  README.md
  app/initializers/analytics.js
  app/routes/application.js
  config/environment.js
  package-lock.json
  package.json
Labels: enhancement

#287 Fixing unexpected closing of AuModal
  package-lock.json
  package.json
Labels: bug

#289 update package version of citaten-plugin
  package-lock.json
  package.json
Labels: bug, dependencies

#288 fixed linting, fixed nan on archive pagination, fixed filtering, fixed return link
  app/components/app-chrome.hbs
  app/controllers/inbox/irg-archive.js
  app/routes/inbox/irg-archive.js
  app/templates/agendapoints/edit.hbs
  app/templates/agendapoints/show.hbs
  app/templates/inbox/irg-archive.hbs
  app/templates/irg-archive/show.hbs
  package-lock.json
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug

#273 changing the geplandOpenbaar of an agendapoint affects the openbaar of a behandeling
  app/components/agenda-manager/edit.hbs
  app/components/agenda-manager/edit.js
Labels: enhancement

#294 Use paper view for intro and outro editor
  app/components/zitting-text-document-container.js
Labels: bug

#293 added validation which enables/disables the delete button of a meeting based on the number of attached published resources
  app/components/delete-meeting.hbs
  app/components/delete-meeting.js
  app/templates/meetings/edit.hbs
Labels: enhancement

#291 bump ember promise helpers to 2.0.0
  package-lock.json
  package.json
Labels: internal
