Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-02, with the labels that each got.

#232 bump regulation and template-variable plugin
  package-lock.json
  package.json
Labels: bug

#237 Bump template variable plugin from 0.1.1 to 0.1.2
  package-lock.json
  package.json
Labels: enhancement

#238 Bump besluit plugin from 0.1.3 to 0.1.4
  package-lock.json
  package.json
Labels: enhancement

#239 Bump ember-rdfa-editor from beta-7 to beta-8
  package-lock.json
  package.json
Labels: enhancement

#240 align both the browserlist and build targets
  config/targets.js
  package-lock.json
  package.json
Labels: internal

#244 Fixing production builds "out of memory" problems
  Dockerfile
  ember-cli-build.js
Labels: bug
