Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-08, with the labels that each got.

#308 Disable closing the edit agendapoint modal when saving
  app/components/agenda-manager/edit.hbs
  app/components/agenda-manager/edit.js
Labels: bug

#311 Addition of an environment banner
  README.md
  app/components/environment-banner.hbs
  app/components/environment-banner.js
  app/components/version-information-overview.hbs
  app/components/version-information-overview.js
  app/styles/app.scss
  app/styles/project/_c-environment-banner.scss
  app/templates/application.hbs
  config/environment.js
Labels: enhancement

#298 Changes for new besluit-type-plugin
  ember-cli-build.js
  package-lock.json
  package.json
  public/assets/ttl/20200120153300-insert-besluit-types.ttl
  public/assets/ttl/20210205102900-new-besluit-types.ttl
Labels: enhancement

#312 Bump editor to 0.61.1
  package-lock.json
  package.json
Labels: internal

#315 Bugfix/make meeting date more clear
  app/components/meeting-form.hbs
  app/components/meeting-form.js
  app/components/zitting/manage-zittingsdata.hbs
  app/components/zitting/manage-zittingsdata.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#316 Bugfix/make meeting date more clear
  app/components/meeting-form.hbs
  app/components/meeting-form.js
  app/components/zitting/manage-zittingsdata.hbs
  app/components/zitting/manage-zittingsdata.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement
