Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-09, with the labels that each got.

#314 Environment banner styling and fixes
  app/components/environment-banner.hbs
  app/components/version-information-overview.hbs
  app/styles/_shame.scss
  app/templates/application.hbs
Labels: bug

#313 Move position of the set vote private checkbox
  app/components/treatment/voting/edit.hbs
Labels: enhancement

#318 extract environment banner functionality and component to seperate repo
  app/components/environment-banner.hbs
  app/components/environment-banner.js
  app/components/version-information-overview.hbs
  app/components/version-information-overview.js
  app/controllers/application.js
  app/templates/application.hbs
  config/environment.js
  package-lock.json
  package.json
Labels: internal

#319 Print preview improvements
  app/components/signatures/publication-confirmation.hbs
  app/styles/_shame.scss
  app/styles/project/_u-print.scss
  app/templates/inbox/agendapoints.hbs
  app/templates/inbox/meetings.hbs
  app/templates/meetings/publish/uittreksels/index.hbs
Labels: enhancement

#320 Ensure meeting is deleted from cache before returning to meeting overview when deleting a meeting
  app/components/delete-meeting.js
Labels: bug

#323 Add release task to package.json
  package.json
Labels: internal

#324 bump editor to 0.63.1 and plugins to latest
  app/styles/app.scss
  package-lock.json
  package.json
Labels: internal

#326 Repair basic RB registry integration
  app/components/document-creator.js
  app/services/regulatory-attachments-fetcher.js
  package-lock.json
  package.json
Labels: bug

#330 Fix selection errors when trying to save with empty selection
  package-lock.json
  package.json
Labels: bug

#331 Fixed bug where the attachment wasn't assigned to the first decision when inserted
  app/components/document-attachments.js
Labels: bug

#328 chore(deps): bump editor and plugins to newest bugfix releases
  package-lock.json
  package.json
Labels: internal

#332 bumps the variable template plugin
  package-lock.json
  package.json
Labels: bug
