Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-05, with the labels that each got.

#267 bumped appuniversum
  app/styles/_shame.scss
  app/styles/project/_c-meeting-chrome.scss
  package-lock.json
  package.json
Labels: internal

#269 fix attachments number in the agendapoints screen
  app/components/attachments-number.js
Labels: bug

#271 Removed style that displayed article number as block
  app/styles/project/_c-template.scss
Labels: bug

#268 Fix alignment of datepicker dialogs in modal windows
  app/components/date-time-picker.hbs
  app/components/zitting/manage-zittingsdata.hbs
  app/templates/inbox/meetings/new.hbs
  package-lock.json
  package.json
Labels: bug

#275 bump editor: improved whitespace handling and table inserts
  package-lock.json
  package.json
Labels: enhancement

#270 Made attachments pill clickable and go to the uploading part of the behandeling
  app/components/behandeling-van-agendapunt.hbs
  app/controllers/meetings/edit/treatment.js
Labels: enhancement

#277 Updated dependency rdfa-date-plugin
  package-lock.json
  package.json
Labels: enhancement
