Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-03, with the labels that each got.

#247 make the template required when creating an agendapoint
  app/components/document-creator.hbs
  app/components/document-creator.js
  app/components/document-creator/form.hbs
Labels: enhancement

#251 improve variable support: add support for multi select codelists
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement

#250 also update article number when reordering articles
  package-lock.json
  package.json
Labels: enhancement

#249 Generate a final preview for the notulen taking into account public behandelings
  app/components/publication-preview.hbs
  app/components/publication-preview.js
  app/components/publication-publish.hbs
  app/components/publication-publish.js
  app/components/publication-signatures.hbs
  app/components/publication-signatures.js
  app/components/signatures/notulen/timeline-step.hbs
  app/components/signatures/notulen/timeline-step.js
  app/components/signatures/publication-confirmation.hbs
  app/components/signatures/signature-confirmation.hbs
  app/components/signatures/timeline-step.hbs
  app/components/signatures/timeline-step.js
  app/controllers/meetings/publish/notulen.js
  app/helpers/human-publication-status.js
  app/helpers/publication-status-color.js
  app/helpers/status-icon-name.js
  app/routes/meetings/publish/notulen.js
  app/serializers/application.js
  app/services/mu-task.js
  app/services/publish.js
  app/templates/meetings/publish/notulen.hbs
  package-lock.json
Labels: enhancement

#252 improved regulation search + removed images from output
  package-lock.json
  package.json
Labels: enhancement

#253 Chore/upgrade roadsign regulation plugin
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug

#254 fix labels in the citation plugin modal
  package-lock.json
  package.json
Labels: bug

#255 fix validation on publishing notulen
  CHANGELOG.md
  app/templates/meetings/publish/notulen.hbs
  package-lock.json
  package.json
Labels: bug

#256 bump roadsign regulation plugin to 0.7.2
  package-lock.json
  package.json
Labels: bug

#257 IRGN: fetch location options from registry codelist
  package-lock.json
  package.json
Labels: enhancement

#258 show actual notulen content for published notulen
  app/controllers/meetings/publish/notulen.js
  app/templates/meetings/publish/notulen.hbs
Labels: bug

#260 Chore/upgrade editor
  CHANGELOG.md
  package-lock.json
  package.json
Labels: internal

#246 bump template and decision type plugin
  app/components/document-creator.js
  app/components/rdfa-editor-container.js
  app/config/editor-profiles.js
  package-lock.json
  package.json
Labels: internal
