Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-12, with the labels that each got.

#379 Fix weird title behaviour in regulatory statements edit page.
  app/controllers/regulatory-statements/edit.js
Labels: bug

#375 add a prompt when a user tries to leave a page with unsaved changes in a document (GN-3740)
  app/controllers/regulatory-statements/edit.js
  app/templates/regulatory-statements/edit.hbs
Labels: enhancement

#373 Feature: non editable published regulatory statements
  app/components/app-chrome.hbs
  app/components/app-chrome.js
  app/components/editor-plugins/regulatory-statements/view.hbs
  app/components/editor-plugins/regulatory-statements/view.js
  app/components/regulatory-statement-link.hbs
  app/components/regulatory-statement-link.js
  app/routes/inbox/agendapoints.js
  app/routes/inbox/regulatory-statements.js
  app/templates/inbox/regulatory-statements.hbs
  app/templates/regulatory-statements/show.hbs
Labels: enhancement

#377 reset back to the url you were on after cancelling redirect
  app/components/confirm-route-leave.js
Labels: bug

#380 hide rs behind feature flag
  Dockerfile
  app/components/rdfa-editor-container.js
  app/controllers/inbox.js
  app/controllers/meetings/publish.js
  app/instance-initializers/features-setup.js
  app/routes/inbox/regulatory-statements.js
  app/routes/regulatory-statements.js
  app/templates/inbox.hbs
  app/templates/meetings/publish.hbs
  config/environment.js
Labels: internal

#378 add archive date to irg archive (GN-3827)
  app/styles/project/_c-template.scss
  app/templates/inbox/irg-archive.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#383 Add archive date to irg archive
  app/styles/project/_c-template.scss
  app/templates/inbox/irg-archive.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#384 Feature/rs revisions
  app/components/app-chrome.hbs
  app/controllers/regulatory-statements/edit.js
  app/controllers/regulatory-statements/revisions.js
  app/router.js
  app/routes/regulatory-statements/edit.js
  app/routes/regulatory-statements/revisions.js
  app/styles/_shame.scss
  app/templates/regulatory-statements/edit.hbs
  app/templates/regulatory-statements/revisions.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#385 Feature/restore old rs
  app/config/custom-inflector-rules.js
  app/controllers/regulatory-statements/revisions.js
  app/utils/replace-uris.js
Labels: enhancement

#386 Feature/create new rs versions
  app/components/document-history.hbs
  app/components/document-history.js
  app/controllers/regulatory-statements/edit.js
  app/controllers/regulatory-statements/revisions.js
  app/controllers/regulatory-statements/show.js
  app/router.js
  app/routes/regulatory-statements/edit/history.js
  app/routes/regulatory-statements/revisions/history.js
  app/services/document-service.js
  app/templates/regulatory-statements/edit.hbs
  app/templates/regulatory-statements/edit/history.hbs
  app/templates/regulatory-statements/revisions.hbs
  app/templates/regulatory-statements/revisions/history.hbs
  app/templates/regulatory-statements/show.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#388 Don't allow participant list insertion if the chairman is not present
  app/components/participation-list/mandataris-row.hbs
  app/components/participation-list/modal.hbs
  app/components/participation-list/modal.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#390 Make title error visible and wrap when content is long
  app/components/agenda-punt-link.hbs
  app/components/editor-document-title.hbs
  app/components/regulatory-statement-link.hbs
  app/helpers/limit-content.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug

#392 Feature/solve inconsistencies
  app/components/document-history.hbs
  app/components/document-history.js
  app/controllers/regulatory-statements/revisions.js
  app/controllers/regulatory-statements/show.js
  app/router.js
  app/routes/regulatory-statements/show/history.js
  app/templates/regulatory-statements/revisions.hbs
  app/templates/regulatory-statements/show.hbs
  app/templates/regulatory-statements/show/history.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#395 Solved revisions not updating until page reload
  app/components/agendapoint-menu.js
  app/templates/agendapoints/edit.hbs
Labels: bug

#397 Feature/support long titles in meeting screen
  app/components/agenda-manager/agenda-table/row.hbs
  app/components/behandeling-van-agendapunt.hbs
  app/components/signatures/timeline-step.hbs
  app/helpers/limit-content.js
  app/templates/meetings/publish/uittreksels/index.hbs
Labels: enhancement
