Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-04, with the labels that each got.

#262 bump appuniversum to 1.0.3
  package-lock.json
  package.json
Labels: internal

#264 Fixed off by one errors on adding agendapoints
  app/components/agenda-manager/agenda-item-form/select-location.js
  app/components/agenda-manager/edit.hbs
Labels: bug

#265 Trim title on validation and on saving Agendapoint
  app/components/document-creator.js
Labels: bug

#266 Bump editor to v0.55.2 and update plugins to new versions
  app/components/rdfa-editor-container.js
  package-lock.json
  package.json
Labels: enhancement

#261 ran npm update
  package-lock.json
  package.json
Labels: internal

#263 improve import flow using updated import plugin
  app/components/rdfa-editor-container.js
  app/components/snippets-notifier.hbs
  app/components/snippets-notifier.js
  app/config/editor-profiles.js
  app/routes/import/edit.js
  app/routes/import/new.js
  app/templates/application.hbs
  app/templates/inbox/agendapoints.hbs
Labels: bug
