Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-10, with the labels that each got.

#329 Rename 'concept' to 'In voorbereiding'
  app/components/app-chrome.hbs
  app/components/editor-status-pill.hbs
  app/components/signatures/publication-status.js
  app/components/signatures/timeline-step.js
  app/helpers/human-publication-status.js
  app/routes/inbox/agendapoints.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#327 Fix/button alignment
  app/components/agenda-manager/edit.hbs
  app/components/manage-intermissions/edit.hbs
  app/components/participation-list/modal.hbs
  app/components/signatures/publication-confirmation.hbs
  app/components/signatures/signature-confirmation.hbs
  app/components/treatment/voting/edit.hbs
  app/components/treatment/voting/modal.hbs
  app/components/treatment/voting/voter-table.hbs
  app/components/zitting/manage-zittingsdata.hbs
  app/styles/_shame.scss
  app/styles/project/_c-meeting-chrome.scss
  app/templates/meetings/edit/intro.hbs
  app/templates/meetings/edit/outro.hbs
  app/templates/meetings/edit/treatment.hbs
Labels: bug

#333 Filter based on validThrough property
  app/services/regulatory-attachments-fetcher.js
Labels: bug

#334 Update toc plugin which fixes issues with overflowing entries
  app/styles/_shame.scss
  package-lock.json
  package.json
Labels: bug

#335 Add RB endpoints to devenv
  config/environment.js
Labels: internal

#338 fix: set start date to planned start on creation
  app/controllers/inbox/meetings/new.js
Labels: bug

#341 Fix regex which matches for generateUuid() in the template
  app/components/document-creator.js
Labels: bug

#342 Fix: prevent the confirm dialog to show up twice when exiting without saving
  app/components/confirm-route-leave.js
  app/utils/is-loading-route.js
Labels: bug

#297 Create revision layout
  app/components/agendapoint-back-link.hbs
  app/components/agendapoint-back-link.js
  app/components/agendapoint-menu.hbs
  app/components/agendapoint-menu.js
  app/components/app-chrome-statement.hbs
  app/components/app-chrome-statement.js
  app/components/app-chrome.hbs
  app/components/behandeling-van-agendapunt.hbs
  app/components/confirm-route-leave.js
  app/components/rdfa-editor-container.hbs
  app/controllers/agendapoints/attachments.js
  app/controllers/agendapoints/edit.js
  app/controllers/agendapoints/revisions.js
  app/controllers/meetings/edit/treatment.js
  app/router.js
  app/routes/agendapoints.js
  app/routes/agendapoints/attachments.js
  app/routes/agendapoints/edit.js
  app/routes/agendapoints/revisions.js
  app/routes/meetings/edit/treatment.js
  app/styles/_shame.scss
  app/styles/project/_c-app-chrome.scss
  app/templates/agendapoints/attachments.hbs
  app/templates/agendapoints/edit.hbs
  app/templates/agendapoints/revisions.hbs
  app/templates/meetings/edit/treatment.hbs
  app/templates/regulatory-statements/edit.hbs
  app/utils/is-loading-route.js
  package-lock.json
  package.json
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#345 Fix infinite pages when printing a meeting
  app/styles/project/_u-print.scss
Labels: bug

#344 fix deprecations
  app/components/acmidm-login-compact.hbs
  app/components/document-attachments.hbs
  app/components/meeting-form.hbs
  app/components/publication-preview.hbs
  app/components/publication-publish.hbs
  app/components/publication-signatures.hbs
  app/components/signatures/publication-confirmation.hbs
  app/components/signatures/published-resource.hbs
  app/components/signatures/signature-confirmation.hbs
  app/components/signatures/timeline-step.hbs
  app/components/snippets-notifier.hbs
  app/routes/inbox/meetings.js
  app/routes/inbox/trash.js
  app/routes/meetings/publish/uittreksels/index.js
  app/templates/agendapoints/show.hbs
  app/templates/inbox/agendapoints.hbs
  app/templates/inbox/agendapoints/new.hbs
  app/templates/inbox/imported.hbs
  app/templates/inbox/meetings.hbs
  app/templates/inbox/regulatory-statements.hbs
  app/templates/inbox/regulatory-statements/new.hbs
  app/templates/inbox/trash.hbs
  app/templates/irg-archive/show.hbs
  app/templates/meetings/publish.hbs
  app/templates/meetings/publish/besluitenlijst.hbs
  app/templates/meetings/publish/notulen.hbs
  app/templates/meetings/publish/uittreksels/index.hbs
  app/templates/meetings/publish/uittreksels/show.hbs
  app/templates/mock-login.hbs
  app/templates/regulatory-statements/show.hbs
  app/templates/switch-login.hbs
Labels: internal

#349 Add export-to-html menu action to regulatory-statements document view
  app/controllers/regulatory-statements/edit.js
  app/templates/agendapoints/attachments.hbs
  app/templates/agendapoints/edit.hbs
  app/templates/agendapoints/revisions.hbs
  app/templates/regulatory-statements/edit.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#346 Bump template-variable-plugin to 0.9.0
  package-lock.json
  package.json
Labels: internal

#350 Bump besluit-plugin to 0.5.7
  package-lock.json
  package.json
Labels: internal

#337 Save document title after edit
  app/components/app-chrome.hbs
  app/components/app-chrome.js
  app/components/document-creator.js
  app/components/editor-document-title.hbs
  app/components/editor-document-title.js
  app/controllers/agendapoints/edit.js
  app/controllers/regulatory-statements/edit.js
  app/controllers/regulatory-statements/show.js
  app/routes/agendapoints/show.js
  app/services/document-service.js
  app/templates/agendapoints/edit.hbs
  app/templates/agendapoints/show.hbs
  app/templates/irg-archive/show.hbs
  app/templates/regulatory-statements/edit.hbs
  app/templates/regulatory-statements/show.hbs
Labels: bug

#352 Bump editor to 0.63.5
  package-lock.json
  package.json
Labels: internal
