Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2022-11, with the labels that each got.

#354 Fix syntax issue that caused error when saving regulatory statement
  app/controllers/regulatory-statements/edit.js
Labels: bug

#357 Update editor to 0.63.7
  package-lock.json
  package.json
Labels: internal

#353 Fix issue with voting overview page where the number of votings are limited to 20
  app/components/treatment/voting/modal.js
  app/models/behandeling-van-agendapunt.js
  app/models/stemming.js
Labels: bug

#358 HOTFIX: fetch all stemmingen and ensure positions of stemmingen stay correct
  app/components/treatment/voting/modal.js
  app/models/behandeling-van-agendapunt.js
  app/models/stemming.js
Labels: bug, hotfix

#355 Feature: decision regulatory statement coupling
  app/components/editor-plugins/regulatory-statements/search-modal.hbs
  app/components/editor-plugins/regulatory-statements/search-modal.js
  app/components/editor-plugins/regulatory-statements/sidebar-insert.hbs
  app/components/editor-plugins/regulatory-statements/sidebar-insert.js
  app/components/editor-plugins/regulatory-statements/view.hbs
  app/components/editor-plugins/regulatory-statements/view.js
  app/components/rdfa-editor-container.js
  app/config/editor-document-default-context.js
  app/editor-plugins/regulatory-statements-plugin/index.js
  app/editor-plugins/regulatory-statements-plugin/inline-components/regulatory-statements-view.js
  app/initializers/editor-plugins.js
  app/models/document-container.js
  app/models/editor-document.js
  app/services/document-service.js
  app/styles/_shame.scss
  config/environment.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#356 adapt query to the new model
  app/services/regulatory-attachments-fetcher.js
Labels: enhancement

#360 Sort regulatory statements by title when inserting a regulatory statement in an agendapoint
  app/components/editor-plugins/regulatory-statements/search-modal.js
Labels: enhancement

#362 Feature/minor improvements
  app/controllers/agendapoints/edit.js
  app/routes/agendapoints/edit.js
  app/routes/agendapoints/show.js
Labels: enhancement

#365 Feature/translation improvements
  app/components/app-chrome.hbs
  app/templates/agendapoints/edit.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#361 When the notulen is published disable the editing
  app/components/meeting-form.hbs
  app/components/meeting-form.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#366 Bugfix: only return title property if this._title is null or undefined
  app/components/editor-document-title.js
Labels: bug

#363 Feature: prevent the duplicate inclusion of regulatory statements in a decision
  app/components/editor-plugins/regulatory-statements/search-modal.hbs
  app/components/editor-plugins/regulatory-statements/search-modal.js
  app/components/editor-plugins/regulatory-statements/sidebar-insert.hbs
  app/services/document-service.js
  package-lock.json
  package.json
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#364 Disable 'insert statement' button if there is no besluit present
  app/components/editor-plugins/regulatory-statements/sidebar-insert.hbs
  app/components/editor-plugins/regulatory-statements/sidebar-insert.js
Labels: bug

#367 Move besluit property in regulatory statement plugin to dynamic getter.
  app/components/editor-plugins/regulatory-statements/sidebar-insert.js
Labels: bug

#368 Update editor to version 0.64.0
  package-lock.json
  package.json
Labels: internal

#369 Update roadsign regulation plugin to version 0.9.5
  package-lock.json
  package.json
Labels: internal

#372 Bump table of contents plugin to 0.5.0
  package-lock.json
  package.json
Labels: internal

#359 When saving an editorDocument retrieve and store its parts in the editor-document model
  app/components/editor-plugins/regulatory-statements/sidebar-insert.js
  app/components/editor-plugins/regulatory-statements/view.js
  app/editor-plugins/regulatory-statements-plugin/inline-components/regulatory-statements-view.js
  app/models/document-container.js
  app/models/editor-document.js
  app/models/versioned-regulatory-statement.js
  app/services/document-service.js
  app/templates/inbox/regulatory-statements.hbs
  package-lock.json
  package.json
Labels: enhancement
