Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2023-01, with the labels that each got.

#399 Hide empty voter divs in notulen preview
  app/styles/_shame.scss
Labels: bug

#400 Add case insensitive sorting to all text-based/title columns
  app/components/agenda-manager/agenda-item-form/select-draft.js
  app/components/editor-plugins/regulatory-statements/search-modal.js
  app/templates/inbox/agendapoints.hbs
  app/templates/inbox/irg-archive.hbs
  app/templates/inbox/meetings.hbs
  app/templates/inbox/regulatory-statements.hbs
  app/templates/inbox/trash.hbs
  app/templates/meetings/publish/uittreksels/index.hbs
Labels: enhancement

#398 Bugfix/rs scrolling issue
  app/templates/regulatory-statements/edit.hbs
  app/templates/regulatory-statements/revisions.hbs
  app/templates/regulatory-statements/show.hbs
Labels: enhancement

#403 Update ember appuniversum to 2.2.0
  package-lock.json
  package.json
Labels: internal

#404 Bump editor to 1.0.0-beta.2 and editor-plugins to 1.0.0-beta.1
  app/config/constants.js
  app/controllers/regulatory-statements/edit.js
  package-lock.json
  package.json
Labels: internal

#406 Update irg-archive date to 18-01-2023
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#405 update editor to 1.0.0-beta.5 and plugins to 1.0.0-beta.3
  app/components/editor-plugins/regulatory-statements/search-modal.hbs
  app/components/zitting-text-document-container.js
  app/config/constants.js
  app/controllers/agendapoints/edit.js
  app/controllers/regulatory-statements/edit.js
  app/styles/app.scss
  config/environment.js
  package-lock.json
  package.json
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: internal

#401 Fix/reg statement design review
  app/components/document-history.hbs
  app/styles/_shame.scss
  app/templates/regulatory-statements/edit.hbs
  app/templates/regulatory-statements/revisions.hbs
Labels: enhancement

#389 Integration of new prosemirror-based editor
  app/components/besluit-document-container.hbs
  app/components/besluit-document-container.js
  app/components/document-creator.js
  app/components/editor-plugins/regulatory-statements/search-modal.hbs
  app/components/editor-plugins/regulatory-statements/sidebar-insert.js
  app/components/editor-plugins/regulatory-statements/view.hbs
  app/components/editor-plugins/regulatory-statements/view.js
  app/components/rdfa-editor-container.hbs
  app/components/rdfa-editor-container.js
  app/components/zitting-text-document-container.hbs
  app/components/zitting-text-document-container.js
  app/config/constants.js
  app/controllers/agendapoints/edit.js
  app/controllers/regulatory-statements/edit.js
  app/editor-plugins/regulatory-statements-plugin/index.js
  app/editor-plugins/regulatory-statements-plugin/inline-components/regulatory-statements-view.js
  app/initializers/editor-plugins.js
  app/models/template.js
  app/routes/inbox/agendapoints/new.js
  app/styles/app.scss
  app/templates/agendapoints/edit.hbs
  app/templates/regulatory-statements/edit.hbs
  config/environment.js
  package-lock.json
  package.json
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#407 Update editor-plugins to 1.0.0 beta 6
  package-lock.json
  package.json
Labels: internal

#408 Increase priority of regulatory statement node in schema
  app/controllers/agendapoints/edit.js
Labels: bug

#411 Add besluit-plugin stylesheet
  app/styles/app.scss
Labels: bug

#402 Add new statuses for the regulatory statements
  app/components/app-chrome.hbs
  app/components/regulatory-statement-status-pill.hbs
  app/components/regulatory-statement-status-pill.js
  app/templates/inbox/regulatory-statements.hbs
  app/templates/regulatory-statements/edit.hbs
  app/templates/regulatory-statements/show.hbs
  app/utils/constants.js
Labels: enhancement

#409 Enable table keymap and allow block content in table cells
  app/components/zitting-text-document-container.js
  app/controllers/agendapoints/edit.js
  app/controllers/regulatory-statements/edit.js
Labels: bug

#413 Update editor to 1.0.0 and plugins to 1.0.0-beta.8
  package-lock.json
  package.json
Labels: internal

#412 Fix i18n of human readable dates
  app/components/app-chrome.hbs
  app/components/app-chrome.js
  app/components/document-history.hbs
  app/components/document-history.js
  app/components/editor-plugins/regulatory-statements/view.hbs
  app/components/editor-plugins/regulatory-statements/view.js
  app/controllers/agendapoints/revisions.js
  app/controllers/inbox/agendapoints.js
  app/controllers/inbox/imported.js
  app/controllers/inbox/regulatory-statements.js
  app/controllers/inbox/trash.js
  app/controllers/regulatory-statements/revisions.js
  app/controllers/regulatory-statements/show.js
  app/helpers/human-friendly-date.js
  app/templates/agendapoints/revisions.hbs
  app/templates/inbox/agendapoints.hbs
  app/templates/inbox/imported.hbs
  app/templates/inbox/regulatory-statements.hbs
  app/templates/inbox/trash.hbs
  app/templates/regulatory-statements/edit.hbs
  app/templates/regulatory-statements/revisions.hbs
  app/templates/regulatory-statements/show.hbs
Labels: bug

#410 Support for displaying which agendapoints are linked to a regulatory statement
  app/components/linked-agendapoints-button.hbs
  app/components/linked-agendapoints-button.js
  app/components/linked-agendapoints-modal.hbs
  app/components/linked-agendapoints-modal.js
  app/helpers/human-friendly-date.js
  app/templates/inbox/regulatory-statements.hbs
  package-lock.json
  package.json
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#414 Reroute irg-archive to login when not authenticated
  app/routes/irg-archive.js
Labels: bug
