Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2023-03, with the labels that each got.

#441 Use new ember-concurrency api
  app/components/administrative-body-select.js
  app/components/agenda-manager/agenda-context.js
  app/components/agenda-manager/agenda-item-form/index.js
  app/components/agenda-manager/agenda-item-form/select-draft.js
  app/components/agenda-manager/agenda-table/row.js
  app/components/agenda-manager/edit.js
  app/components/attachments-number.js
  app/components/behandeling-van-agendapunt.js
  app/components/delete-meeting.js
  app/components/document-attachments.js
  app/components/document-creator.js
  app/components/document-history.js
  app/components/editor-plugins/regulatory-statements/search-modal.js
  app/components/manage-intermissions/edit.js
  app/components/manage-intermissions/index.js
  app/components/meeting-form.js
  app/components/participation-list/functionaris-selector.js
  app/components/participation-list/mandataris-selector.js
  app/components/regulatory-statement-status-pill.js
  app/components/signatures/timeline-step.js
  app/components/treatment/voting/modal.js
  app/components/zitting-link.js
  app/components/zitting-text-document-container.js
  app/controllers/agendapoints/edit.js
  app/controllers/agendapoints/revisions.js
  app/controllers/agendapoints/show.js
  app/controllers/inbox/agendapoints.js
  app/controllers/inbox/irg-archive.js
  app/controllers/inbox/meetings/new.js
  app/controllers/inbox/regulatory-statements.js
  app/controllers/meetings/edit/intro.js
  app/controllers/meetings/edit/outro.js
  app/controllers/meetings/publish/agenda.js
  app/controllers/meetings/publish/besluitenlijst.js
  app/controllers/meetings/publish/notulen.js
  app/controllers/meetings/publish/uittreksels/show.js
  app/controllers/mock-login.js
  app/controllers/regulatory-statements/edit.js
  app/controllers/regulatory-statements/revisions.js
  app/controllers/regulatory-statements/show.js
  app/helpers/relationship-resource.js
  app/routes/agendapoints/revisions.js
  app/services/document-service.js
  app/services/edit-stemming.js
  app/services/mu-task.js
  app/services/publish.js
  app/services/regulatory-attachments-fetcher.js
Labels: internal

#439 Update internal regulatory statement to support new editor API
  app/components/editor-plugins/regulatory-statements/search-modal.hbs
  app/components/editor-plugins/regulatory-statements/sidebar-insert.js
  app/components/editor-plugins/regulatory-statements/view.hbs
  app/components/editor-plugins/regulatory-statements/view.js
  app/templates/agendapoints/edit.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug

#444 feat(editor): bump to 3.4 and activate all the new features
  app/components/rdfa-editor-container.hbs
  app/components/rdfa-editor-container.js
  app/controllers/agendapoints/edit.js
  app/controllers/regulatory-statements/edit.js
  app/templates/agendapoints/edit.hbs
  app/templates/regulatory-statements/edit.hbs
  package-lock.json
  package.json
Labels: enhancement
