Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2023-02, with the labels that each got.

#415 Addition of not-found route
  app/components/application-header.hbs
  app/components/application-header.js
  app/components/vo-page.hbs
  app/router.js
  app/templates/inbox.hbs
  app/templates/not-found.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#416 Add error routes to agendapoints, regulatory statements, meetings and the irg-archive
  app/adapters/application.js
  app/components/not-found-warning.hbs
  app/components/not-found-warning.js
  app/components/vo-page.hbs
  app/components/vo-page.js
  app/routes/agendapoints.js
  app/routes/regulatory-statements/edit.js
  app/templates/agendapoints-error.hbs
  app/templates/irg-archive/error.hbs
  app/templates/meetings/error.hbs
  app/templates/not-found.hbs
  app/templates/regulatory-statements/error.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#418 Disable regulatory statement insert when its feature flag is disabled
  app/controllers/agendapoints/edit.js
Labels: bug

#421 Show unsaved changes correctly
  app/components/app-chrome.hbs
  app/controllers/agendapoints/edit.js
  app/templates/agendapoints/edit.hbs
Labels: bug

#422 bump editor to v2.1.2 and plugins to v2.1.1
  package-lock.json
  package.json
Labels: internal

#425 Hotfix: trim whitespace out of templates before instantiating them
  app/components/document-creator.js
Labels: bug

#428 Hotfix: update plugins to 2.1.2 to solve codelist bug
  package-lock.json
  package.json
Labels: bug

#429 Hotfix: trim whitespace out of templates before instantiating them
  app/components/document-creator.js
Labels: bug

#427 GN-4088: Fix backlink of print
  app/components/extracts/print-view.hbs
Labels: bug

#426 Internal/prevent hardcoded strings
  .template-lintrc.js
  app/components/administrative-body-select.hbs
  app/components/agenda-manager/agenda-table/row.hbs
  app/components/agendapoint-menu.hbs
  app/components/application-header.hbs
  app/components/contact-form.hbs
  app/components/document-history.hbs
  app/components/editor-document-title.hbs
  app/components/extracts/print-view.hbs
  app/components/manage-intermissions/edit.hbs
  app/components/not-found-warning.hbs
  app/components/participation-list/functionaris-selector.hbs
  app/components/participation-list/modal.hbs
  app/components/print-view/print-header.hbs
  app/components/print-view/signature.hbs
  app/components/signatures/notulen/behandelingen-list.hbs
  app/components/signatures/published-resource.hbs
  app/components/snippets-notifier.hbs
  app/components/treatment/voting/manage-voters.hbs
  app/components/vo-page.hbs
  app/components/zitting-link.hbs
  app/components/zitting/manage-zittingsdata.hbs
  app/templates/agendapoints/revisions.hbs
  app/templates/agendapoints/show.hbs
  app/templates/contact.hbs
  app/templates/inbox/loading.hbs
  app/templates/inbox/meetings.hbs
  app/templates/irg-archive/show.hbs
  app/templates/legaal/cookieverklaring.hbs
  app/templates/legaal/disclaimer.hbs
  app/templates/legaal/toegankelijkheidsverklaring.hbs
  app/templates/login.hbs
  app/templates/meetings/publish.hbs
  app/templates/meetings/publish/notulen.hbs
  app/templates/mock-login.hbs
  app/templates/print/uittreksel-error.hbs
  app/templates/switch-login.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: internal

#432 Update ember-environment-banner to 0.2.0
  config/environment.js
  package-lock.json
  package.json
Labels: internal
