Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2023-05, with the labels that each got.

#458 Add chrome hacks plugin to GN
  app/components/rdfa-editor-container.js
  package-lock.json
  package.json
Labels: bug

#456 configure plugins without env variables
  app/controllers/agendapoints/edit.js
  app/controllers/regulatory-statements/edit.js
  app/templates/agendapoints/edit.hbs
  app/templates/regulatory-statements/edit.hbs
  config/environment.js
  package-lock.json
  package.json
Labels: enhancement, breaking

#457 Add au-modal-container and disable deprecation warnings for modal wormhole version
  app/templates/application.hbs
  ember-cli-build.js
Labels: internal

#464 Fix problem with powerselect not appearing
  app/styles/_shame.scss
Labels: bug

#467 Add image base url to env
  config/environment.js
Labels: bug

#469 Add date plugin to zitting-text-document-container and fix date config error
  app/components/zitting-text-document-container.hbs
  app/components/zitting-text-document-container.js
Labels: bug

#471 Update ember-acmidm-login to v2
  app/components/acmidm-login-compact.hbs
  app/components/application-header.hbs
  app/components/application-header.js
  app/router.js
  app/routes/authorization/callback.js
  app/routes/authorization/login.js
  app/routes/authorization/logout.js
  app/routes/authorization/switch.js
  app/routes/switch-login.js
  app/services/session.js
  app/templates/login.hbs
  app/templates/meetings/publish.hbs
  app/templates/switch-login.hbs
  app/utils/acmidm.js
  config/environment.js
  package-lock.json
  package.json
  proxy/torii-authorization.conf
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: internal
