Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2023-06, with the labels that each got.

#475 Fix agendapoint title saving
  app/controllers/agendapoints/edit.js
Labels: bug

#486 Bump editor to 3.8.1 and editor-plugins to 7.2.0
  app/components/zitting-text-document-container.js
  app/controllers/agendapoints/edit.js
  app/controllers/regulatory-statements/edit.js
  package-lock.json
  package.json
Labels: internal

#494 Place the date on the right of the signer
  app/components/signatures/signed-resource.hbs
Labels: enhancement

#493 Hide hash on signed resource
  app/components/signatures/signed-resource.hbs
Labels: enhancement

#501 Update `@lblod/ember-rdfa-editor` to 3.10.0 and `@lblod/ember-rdfa-editor-lblod-plugins` to 8.1.0
  package-lock.json
  package.json
Labels: internal

#496 GN-4359: improve publish page translations
  app/components/publishing-log-document-name.hbs
  app/components/publishing-log-document-name.js
  app/components/signatures/agenda/timeline-step.hbs
  app/components/signatures/notulen/behandelingen-list.hbs
  app/components/signatures/publication-status.js
  app/components/signatures/timeline-step.hbs
  app/components/signatures/timeline-step.js
  app/controllers/meetings/publish/notulen.js
  app/controllers/meetings/publish/publication-actions/index.js
  app/helpers/human-publication-status.js
  app/templates/meetings/publish.hbs
  app/templates/meetings/publish/agenda.hbs
  app/templates/meetings/publish/besluitenlijst.hbs
  app/templates/meetings/publish/notulen.hbs
  app/templates/meetings/publish/publication-actions/detail.hbs
  app/templates/meetings/publish/publication-actions/index.hbs
  app/templates/meetings/publish/uittreksels/index.hbs
  app/templates/meetings/publish/uittreksels/show.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug

#510 fix translation issues on publication actions page
  translations/nl-BE.yaml
Labels: bug

#503 Make design of publication-actions page consistent with designs of other publication pages
  app/templates/meetings/publish/publication-actions/index.hbs
Labels: enhancement

#499 GN-4362 fix signatures disappearing after publishing
  app/controllers/meetings/publish/notulen.js
Labels: bug

#511 GN-4403: use correct config for variables
  app/controllers/agendapoints/edit.js
  app/controllers/regulatory-statements/edit.js
  config/environment.js
  package-lock.json
  package.json
Labels: bug
