Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2023-08, with the labels that each got.

#542 Update editor plugins to 8.4.2
  package-lock.json
  package.json
Labels: internal

#551 GN-4451: fix rendered templates not showing in roadsign modal
  package-lock.json
  package.json
Labels: bug

#558 GN-4472: Optimize loading of meeting page
  .gitignore
  app/adapters/application.js
  app/components/agenda-manager/agenda-context.js
  app/components/agenda-manager/agenda-table/row.js
  app/components/behandeling-van-agendapunt.hbs
  app/components/behandeling-van-agendapunt.js
  app/components/meeting-form.hbs
  app/components/meeting-form.js
  app/components/treatment/voting/modal.hbs
  app/components/treatment/voting/modal.js
  app/components/zitting/manage-zittingsdata.js
  app/models/behandeling-van-agendapunt.js
  app/models/zitting.js
  app/routes/meetings/edit.js
  app/templates/meetings/edit.hbs
Labels: enhancement

#563 feat(deps): update editor and plugins
  app/controllers/agendapoints/edit.js
  app/controllers/regulatory-statements/edit.js
  app/templates/agendapoints/edit.hbs
  app/templates/regulatory-statements/edit.hbs
  package-lock.json
  package.json
Labels: enhancement
