Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2024-11, with the labels that each got.

#751 `zitting-text-document-container`: add `emberApplication` plugin
  .changeset/six-crabs-think.md
  app/components/zitting-text-document-container.js
Labels: enhancement

#753 bugfix: ensure decision templates get correctly instantiated upon IV creation
  .changeset/sweet-boxes-rush.md
  app/api/installatievergadering.js
Labels: bug

#752 GN-5153: only trigger event handlers of snippet actions once
  .changeset/calm-bikes-move.md
  package-lock.json
  package.json
Labels: internal

#757 Disable creation of IV if not applicable
  .changeset/real-buses-invite.md
  app/controllers/inbox/meetings.js
  app/templates/inbox/meetings.hbs
Labels: enhancement

#759 Add agendapoint numbers to download table
  .changeset/dirty-vans-boil.md
  app/styles/_shame.scss
  app/templates/meetings/download/index.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#760 GN-5166: adjustments to IV fraction tables
  .changeset/violet-buckets-applaud.md
  app/config/mandatee-table-config.js
Labels: bug

#763 GN-5209: fix citation plugin issues
  .changeset/early-pans-wink.md
  app/controllers/regulatory-statements/edit.js
  app/services/editor/agendapoint.js
  package-lock.json
  package.json
Labels: bug

#765 feat(meeting-creation): only allow bestuursorganen active at planned start date
  .changeset/chatty-lemons-return.md
  app/components/administrative-body-select.hbs
  app/components/administrative-body-select.js
  app/controllers/inbox/meetings/new.js
  app/models/bestuursorgaan.js
  app/templates/inbox/meetings/new.hbs
Labels: enhancement

#766 Ember application plugin was wrongly configured on custom voting and zitting text container
  .changeset/rich-pandas-protect.md
  app/components/zitting-text-document-container.js
  app/controllers/meetings/edit/custom-voting.js
Labels: bug

#768 Fix codelist and locations in agendapoint editor
  .changeset/swift-coins-press.md
  app/templates/agendapoints/edit.hbs
Labels: bug

#773 GN-5239: headless-editor - add necessary RDFa plugins
  .changeset/eight-forks-live.md
  app/services/editor/agendapoint.js
Labels: bug

#769 GN-5217: person variable adjustments
  .changeset/metal-onions-guess.md
  package-lock.json
  package.json
Labels: enhancement

#772 Update template UUID instantiator
  .changeset/forty-starfishes-eat.md
  .changeset/metal-onions-guess.md
  .changeset/rich-masks-grab.md
  package-lock.json
  package.json
Labels: bug, internal

#778 GN-5275: RMW mandatee tables - move bekrachtigtAanstellingVan predicate to 'eedafleggingen' table
  .changeset/silly-owls-pull.md
  app/components/meeting-form.js
  app/config/mandatee-table-config.js
Labels: enhancement

#780 FIx bug when creating a IV with Ronse and Voeren
  .changeset/angry-guests-poke.md
  app/api/installatievergadering.js
Labels: bug

#779 mandatee sparql-queries: don't query tombstones
  .changeset/honest-frogs-smile.md
  app/config/mandatee-table-config.js
Labels: bug

#781 Update editor to version 10.9.0
  .changeset/nice-pumas-fix.md
  package-lock.json
  package.json
Labels: internal
