Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2024-10, with the labels that each got.

#720 GN-5005: reworked snippet data-model + support for ordered snippets
  .changeset/angry-lemons-hang.md
  package-lock.json
  package.json
Labels: enhancement

#725 GN-5089: add config for fraction splitting
  app/config/constants.js
  app/config/mandatee-table-config.js
  app/utils/promises.js
Labels: enhancement

#711 GN-4985: IV LMB queries
  .changeset/early-students-marry.md
  app/components/inauguration-meeting/synchronization.js
  app/config/constants.js
  app/config/mandatee-table-config.js
  app/controllers/agendapoints/edit.js
  app/utils/editor-utils.js
  app/utils/mandataris-rangorde.js
  app/utils/promises.js
  app/utils/sparql.js
Labels: enhancement

#727 LMB GR config: ensure bestuursfunctie is filtered on 'gemeenteraadslid' where necessary
  .changeset/two-bottles-raise.md
  app/config/mandatee-table-config.js
Labels: bug

#729 GN-5045: rangorde gemeenteraadsleden
  .changeset/little-ties-collect.md
  app/config/mandatee-table-config.js
  app/utils/mandataris-rangorde.js
  app/utils/sparql.js
Labels: enhancement

#730 Additional LMB IV GR corrections
  .changeset/fresh-geese-develop.md
  .changeset/odd-experts-ring.md
  .changeset/odd-terms-buy.md
  .changeset/sixty-ears-jam.md
  app/config/constants.js
  app/config/mandatee-table-config.js
Labels: bug, enhancement

#735 Add focus mode to the meeting form
  .changeset/tough-clouds-pay.md
  app/components/behandeling-van-agendapunt.hbs
  app/components/meeting-form.hbs
  app/components/meeting-form.js
  app/components/with-tooltip.hbs
  app/components/with-tooltip.js
  app/controllers/meetings/edit.js
  app/templates/meetings/edit.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#739 Made delete meeting work again
  .changeset/plenty-terms-relate.md
  app/components/delete-meeting-modal.hbs
  app/components/delete-meeting-modal.js
  app/components/delete-meeting.hbs
  app/components/delete-meeting.js
  app/components/document-history.hbs
  app/components/meeting-form.hbs
  app/components/meeting-form.js
  translations/en-us.yaml
Labels: bug

#741 IV: implement more extendable way to determine correct bestuursorgaan
  .changeset/clean-kings-turn.md
  app/config/constants.js
  app/routes/inbox/meetings/new-inauguration.js
Labels: enhancement

#740 fix(lmb-tables): adjust fractie-splitsing query
  .changeset/clean-kings-turn.md
  .changeset/slow-seals-bathe.md
  app/config/constants.js
  app/config/mandatee-table-config.js
  app/routes/inbox/meetings/new-inauguration.js
Labels: bug

#736 GN-5088: add LMB table configs for the RMW IV
  .changeset/clean-kings-turn.md
  .changeset/fair-boxes-sleep.md
  .changeset/slow-seals-bathe.md
  app/components/inauguration-meeting/synchronization.js
  app/config/constants.js
  app/config/mandatee-table-config.js
  app/routes/inbox/meetings/new-inauguration.js
  app/services/editor/agendapoint.js
  app/utils/editor-utils.js
Labels: enhancement
