Repository lblod/frontend-gelinkt-notuleren, pull requests merged in 2025-01, with the labels that each got.

#796 Add copy parts to the agendapoint
  .changeset/quiet-news-compete.md
  app/components/decision-copy.gjs
  app/controllers/meetings/download/copy.js
  app/router.js
  app/routes/agendapoints/copy.js
  app/templates/agendapoints/copy.hbs
  app/templates/agendapoints/edit.hbs
  app/templates/meetings/download/copy.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: enhancement

#801 Fix incorrect error handling in template-fetcher service
  .changeset/curvy-lizards-suffer.md
  app/services/template-fetcher.js
Labels: bug

#792 Bugfix/autofill variable bug
  .changeset/flat-tomatoes-develop.md
  app/controllers/agendapoints/edit.js
  app/services/editor/agendapoint.js
  app/templates/agendapoints/edit.hbs
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug

#812 Move to builtin ember types
  .changeset/bright-brooms-laugh.md
  .changeset/hot-trainers-pull.md
  app/app.js
  package-lock.json
  package.json
  tsconfig.json
Labels: internal

#823 GN-5228: fix selection issues when moving articles
  .changeset/green-tips-allow.md
  package-lock.json
  package.json
Labels: bug

#822 Fix issues related to decision article uri generation
  .changeset/funny-roses-give.md
  .changeset/honest-mice-travel.md
  app/services/editor/agendapoint.js
  app/templates/agendapoints/edit.hbs
  package-lock.json
  package.json
Labels: bug

#820 Remove `ember-drag-drop` dependency
  .changeset/early-snails-cheat.md
  app/components/agenda-manager/agenda-context.js
  app/components/agenda-manager/agenda-table/body.hbs
  app/components/agenda-manager/agenda-table/header.hbs
  app/components/agenda-manager/agenda-table/row.hbs
  app/styles/_shame.scss
  app/styles/app.scss
  app/styles/project/_c-meeting-chrome.scss
  app/styles/project/_c-sortable.scss
  config/environment.js
  package-lock.json
  package.json
  tsconfig.json
Labels: internal

#824 Update `@lblod/ember-rdfa-editor-lblod-plugins` to version 26.5.0
  .changeset/nasty-zebras-rhyme.md
  package-lock.json
  package.json
Labels: internal

#821 Use in element to fix rb copy parts
  .changeset/cold-toes-happen.md
  app/components/copy-parts/section.gjs
  app/components/rb-copy-parts.gjs
  app/controllers/regulatory-statements/copy.js
  app/templates/regulatory-statements/edit.hbs
  app/utils/copy-parts-update.js
  translations/en-us.yaml
  translations/nl-BE.yaml
Labels: bug
